### ISSUE TITLE
Usage instructions unclear

### ISSUE THREAD

**Issue by Klaster1** [Djiit/vscode-custom-prompts#12]
Sorry for this question, but I find it unclear on how to use the extension. Do I have to type the command name every time I want to use a custom instruction, like so `#selection @customPrompts /custom inlineTestCafeSteps`? I expected for extension suggest the instruction to choose, which I wasn't able to achieve.

**Comment by Djiit** [comment]
Hello, and thank you for your feedback!

I had an errror in the README. Can you try again with `@customPrompts /load inlineTestCafeSteps` (load instead of custom)

The `@customPrompts /load` part is sticky and should stay in the chat dialog when you hit enter.

I'll add more example, and also a /list command to list available prompts.

**Comment by Djiit** [comment]
Readme updated on [v0.3.1](https://marketplace.visualstudio.com/items?itemName=Djiit.vscode-custom-prompts); could you please try again ?

**Comment by Klaster1** [comment]
OK, got it working! I was missing a slash before the command name, you have it wrong even in the comment above 😉 So it seems that users have to remember the command name and enter it every time? If true, that's a huge let down - no way am I gonna remember! That's exactly what autocomplete and fuzzy search exist for.

Edit: found akosyakov.myprompts, it works much better and exactly as I expected. No offense.

**Comment by Djiit** [comment]
Glad to read it :) Thanks
